'use strict';

/**
 * Generate the _dopamine-functions.scss content from config.
 */
function generateSassFunctions(config) {
  const vpMin = config.viewport.min;
  const vpMax = config.viewport.max;

  return [
    `// ================================================`,
    `// Generated by Dopamine Fluid`,
    `// Default viewport: ${vpMin}px – ${vpMax}px`,
    `// ================================================`,
    ``,
    `@use "sass:math";`,
    ``,
    `/// Fluid clamp value that scales linearly between two viewport widths.`,
    `///`,
    `/// @param {Number} $min - Minimum value in pixels`,
    `/// @param {Number} $max - Maximum value in pixels`,
    `/// @param {Number} $vpMin [${vpMin}] - Minimum viewport width in pixels`,
    `/// @param {Number} $vpMax [${vpMax}] - Maximum viewport width in pixels`,
    `/// @return {String} - CSS clamp() value`,
    `///`,
    `/// @example scss`,
    `///   font-size: fluid(16, 48);`,
    `///   padding: fluid(12, 32);`,
    `///   font-size: fluid(32, 96, 480, 1920); // custom viewport`,
    ``,
    `@function fluid($min, $max, $vpMin: ${vpMin}, $vpMax: ${vpMax}) {`,
    `  $minRem: math.div($min, 16) * 1rem;`,
    `  $maxRem: math.div($max, 16) * 1rem;`,
    `  $slope: math.div(($max - $min), ($vpMax - $vpMin));`,
    `  $intercept: math.div($min - $slope * $vpMin, 16);`,
    `  $vw: $slope * 100;`,
    ``,
    `  @if $intercept == 0 {`,
    `    @return clamp(#{$minRem}, #{$vw}vw, #{$maxRem});`,
    `  } @else if $intercept > 0 {`,
    `    @return clamp(#{$minRem}, calc(#{$vw}vw + #{$intercept * 1rem}), #{$maxRem});`,
    `  } @else {`,
    `    @return clamp(#{$minRem}, calc(#{$vw}vw - #{$intercept * -1rem}), #{$maxRem});`,
    `  }`,
    `}`,
    ``,
  ].join('\n');
}

module.exports = { generateSassFunctions };
